version: "3.7"

services:
  instagram-analyzer:
    # Substitua pelo seu usuário real do Docker Hub se for diferente
    image: pedroleonpython/instagram-analyzer-saas:latest
    networks:
      - unfeknet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        # Domínio configurado
        - traefik.http.routers.instagram-analyzer.rule=Host(`spot.unfek.com.br`)
        - traefik.http.routers.instagram-analyzer.entrypoints=websecure
        - traefik.http.routers.instagram-analyzer.tls.certresolver=letsencryptresolver
        # Nginx roda na porta 80 internamente
        - traefik.http.services.instagram-analyzer.loadbalancer.server.port=80
        - traefik.http.services.instagram-analyzer.loadbalancer.passHostHeader=true

networks:
  unfeknet:
    external: true
